### ISSUE TITLE
Getting Started Guide

### ISSUE THREAD

**Issue by jjfarrell** [macarthur-lab/gnomad_qc#4]
Thanks for making these scripts available!  Is there any documentation or a tutorial available on how to use these gnomad_qc scripts? An overview and some examples on how these scripts work would be helpful to get started.

Starting with a vcf, what are the steps involved to run through all the gnomad_qc scripts....

1. What are the steps to import the VCF  to a matrix table? There also seems to be some steps involving coverage files.
2.  What are the steps/command line to run the sample qc? 
3.  What are the steps to run the variant qc for SNVs/ indels?

**Comment by gtiao** [comment]
Thanks for the suggestion! We've been meaning to post these guidelines for a while and have finally summarized the repo, including the rough order in which the scripts were run, in the README. Have a look and let us know if you have questions after reading through it.

**Comment by chadisaad** [comment]
Thanks for the valuable ressources ! I'm opening again the issue to ask if there is any updated guidelines on how to run the whole workflow on our datasets ? thanks
