### ISSUE TITLE
AN (and related INFO fields) should be of 'Number=1'

### ISSUE THREAD

**Issue by nawatts** [macarthur-lab/gnomad_qc#5]
Moving this from macarthur-lab/gnomadjs#314

> Although the VCF 4.2 spec does not provide specific information about the count of expected values, it is implied through the definition of AN ("Total number of alleles in called genotypes"), that there would be one AN value per VCF row. The VCF4.3 spec is more explicit about the reserved info keys, and actually does clarify that AB should be of Number=1
>
> AN fields in the gnomad r2.0.2 were of Number=1, but in r2.1, they are Number=A (but it looks like there are only ever one value for these per row.

@bpow

**Comment by konradjk** [comment]
I think I caught that #2 should close this?

**Comment by konradjk** [comment]
Resolved by #2
